image: python:slim-bullseye

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Cache the installed packages too
cache:
  key:
    files:
      - pyproject.toml
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

  # Need to install GCC for cfelpyutils
  - apt-get update
  - apt-get install -y gcc g++

test:
  script:
    - pip install '.[test]'
    - python -m pytest .
