# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'damnit/gui/new_context_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.template_rb = QtWidgets.QRadioButton(Dialog)
        self.template_rb.setChecked(True)
        self.template_rb.setObjectName("template_rb")
        self.verticalLayout_2.addWidget(self.template_rb)
        self.template_list = QtWidgets.QListWidget(Dialog)
        self.template_list.setObjectName("template_list")
        self.verticalLayout_2.addWidget(self.template_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.template_other_inst_cb = QtWidgets.QCheckBox(Dialog)
        self.template_other_inst_cb.setObjectName("template_other_inst_cb")
        self.horizontalLayout_3.addWidget(self.template_other_inst_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proposal_rb = QtWidgets.QRadioButton(Dialog)
        self.proposal_rb.setObjectName("proposal_rb")
        self.horizontalLayout.addWidget(self.proposal_rb)
        self.proposal_edit = QtWidgets.QLineEdit(Dialog)
        self.proposal_edit.setEnabled(False)
        self.proposal_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.proposal_edit.setObjectName("proposal_edit")
        self.horizontalLayout.addWidget(self.proposal_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_rb = QtWidgets.QRadioButton(Dialog)
        self.file_rb.setObjectName("file_rb")
        self.verticalLayout_3.addWidget(self.file_rb)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_edit = QtWidgets.QLineEdit(Dialog)
        self.file_edit.setEnabled(False)
        self.file_edit.setObjectName("file_edit")
        self.horizontalLayout_2.addWidget(self.file_edit)
        self.browse_button = QtWidgets.QPushButton(Dialog)
        self.browse_button.setEnabled(False)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_2.addWidget(self.browse_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.file_rb.toggled['bool'].connect(self.browse_button.setEnabled) # type: ignore
        self.proposal_rb.toggled['bool'].connect(self.proposal_edit.setEnabled) # type: ignore
        self.template_rb.toggled['bool'].connect(self.template_list.setEnabled) # type: ignore
        self.template_rb.toggled['bool'].connect(self.template_other_inst_cb.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Create a new context file..."))
        self.template_rb.setText(_translate("Dialog", "From a template:"))
        self.template_other_inst_cb.setText(_translate("Dialog", "Show templates for other instruments"))
        self.proposal_rb.setText(_translate("Dialog", "Copy from proposal number:"))
        self.proposal_edit.setPlaceholderText(_translate("Dialog", "1234"))
        self.file_rb.setText(_translate("Dialog", "Select a .py file:"))
        self.browse_button.setText(_translate("Dialog", "Browse"))
