# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 265)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proposal_rb = QtWidgets.QRadioButton(Dialog)
        self.proposal_rb.setChecked(True)
        self.proposal_rb.setObjectName("proposal_rb")
        self.horizontalLayout.addWidget(self.proposal_rb)
        self.proposal_edit = QtWidgets.QLineEdit(Dialog)
        self.proposal_edit.setObjectName("proposal_edit")
        self.horizontalLayout.addWidget(self.proposal_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.folder_rb = QtWidgets.QRadioButton(Dialog)
        self.folder_rb.setObjectName("folder_rb")
        self.verticalLayout_2.addWidget(self.folder_rb)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.folder_edit = QtWidgets.QLineEdit(Dialog)
        self.folder_edit.setEnabled(False)
        self.folder_edit.setObjectName("folder_edit")
        self.horizontalLayout_2.addWidget(self.folder_edit)
        self.browse_button = QtWidgets.QPushButton(Dialog)
        self.browse_button.setEnabled(False)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_2.addWidget(self.browse_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.proposal_rb.toggled['bool'].connect(self.proposal_edit.setEnabled) # type: ignore
        self.folder_rb.toggled['bool'].connect(self.folder_edit.setEnabled) # type: ignore
        self.folder_rb.toggled['bool'].connect(self.browse_button.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Please select the data to open:"))
        self.proposal_rb.setText(_translate("Dialog", "Open proposal number:"))
        self.folder_rb.setText(_translate("Dialog", "Open DAMNIT folder:"))
        self.browse_button.setText(_translate("Dialog", "Browse"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>DAMNIT will open an existing database if this folder contains <span style=\" font-family:\'Source Code Pro\';\">runs.sqlite</span> and <span style=\" font-family:\'Source Code Pro\';\">context.py</span>, or create a new database if not.</p></body></html>"))
